### ISSUE TITLE
Insufficient number of endpoints

### ISSUE THREAD

**Issue by kastomm** [dariocavada/cordova-plugin-usbserial#1]
Hey Dario,

not sure if your still active here but I just got this plugin working on android, it works well on arduino's but if I connect it to a printer or other device it gives me an error for "Insufficient number of endpoints (1)" or "Insufficient number of endpoints (2)" depending on the device

I tried looking through the plugin but cant find the files that are responsible for setting the end points any help would be appreciated

Thanks

Aman

**Comment by dariocavada** [comment]
I've tried the original plugin some days ago with Android 9 connected to Arduino and it works too.
I think the plugin will work only using specific hardware (like arduino). If you look inside a code there are some specific hardcoded drivers :

`public void run() {
				// get UsbManager from Android
				manager = (UsbManager) cordova.getActivity().getSystemService(Context.USB_SERVICE);
				UsbSerialProber prober;

				if (opts.has("vid") && opts.has("pid")) {
					ProbeTable customTable = new ProbeTable();
					Object o_vid = opts.opt("vid"); //can be an integer Number or a hex String
					Object o_pid = opts.opt("pid"); //can be an integer Number or a hex String
					int vid = o_vid instanceof Number ? ((Number) o_vid).intValue() : Integer.parseInt((String) o_vid,16);
					int pid = o_pid instanceof Number ? ((Number) o_pid).intValue() : Integer.parseInt((String) o_pid,16);
					String driver = opts.has("driver") ? (String) opts.opt("driver") : "CdcAcmSerialDriver";

					if (driver.equals("FtdiSerialDriver")) {
						customTable.addProduct(vid, pid, FtdiSerialDriver.class);
					}
					else if (driver.equals("CdcAcmSerialDriver")) {
						customTable.addProduct(vid, pid, CdcAcmSerialDriver.class);
					}
					else if (driver.equals("Cp21xxSerialDriver")) {
                    	customTable.addProduct(vid, pid, Cp21xxSerialDriver.class);
					}
					else if (driver.equals("ProlificSerialDriver")) {
                    	customTable.addProduct(vid, pid, ProlificSerialDriver.class);
					}
					else if (driver.equals("Ch34xSerialDriver")) {
						customTable.addProduct(vid, pid, Ch34xSerialDriver.class);
					}`
