### ISSUE TITLE
Building giving failed

### ISSUE THREAD

**Issue by nik-hal** [dariocavada/cordova-plugin-usbserial#2]
BUILD FAILED in 1s
/platforms/android/gradlew: Command failed with exit code 1 Error output:
/platforms/android/app/src/main/java/com/dchs/usbserial/UsbSerial.java:45: error: cannot find symbol
	private final String TAG = Serial.class.getSimpleName();
	                           ^
  symbol:   class Serial
  location: class UsbSerial
/platforms/android/app/src/main/java/com/dchs/usbserial/UsbSerial.java:88: error: cannot find symbol
					Serial.this.updateReceivedData(data);
					^
  symbol: class Serial
2 errors

FAILURE: Build failed with an exception.

So how to fix this issue?

**Comment by mrblc** [comment]
Sent pull request to fix this and 3 other issues.

**Comment by dariocavada** [comment]
Merged the pull request
